//HERE I SAVE THE HEADER AND FOOTERS TO BE USED AS VARIABLES IN THE TINYMCE OUTPUT

var htmlhead1 = `<!DOCTYPE html>` + `<html>` + `<head>` + `<title id="title">`;

//THE TITLE GETS INSERTD HERE

var htmlhead2 = `</title>` + `<script src="https://www.biblegateway.com/public/link-to-us/tooltips/bglinks.js" type="text/javascript">` + `</script>` + `<link href="../style/style.css" rel="stylesheet">` + `<link href="../style/hoverStyle.css" rel="stylesheet">` + `<link href="../style/navigation&buttons.css" rel="stylesheet">` + `<link href="../style/contextMenu.css" rel="stylesheet">` + `</head>` + `<body>` + `<header>` + `<!--CONTEXT MENU-->` + `<ol class='custom-menu'>` + `<li id="hideSub">Sub-Timeline</li>` + `<li id="hideRow">Hide this Timeline</li>` + `<li id="soloRow">Solo</li>` + `<li id="showDetails">Details</li>` + `<li id="allRestore" class="refreshBtn">Restore All</li>` + `<li id="summaryCM" class="summaryCM">Show Summary Timeline</li>` + `</ol>` + `<nav>` + `<span>` + `<button id="navbutton">&#9776;</button>` + `<h2 style="display: inline">`

//THE HEADING GETS INSERTD HERE

var htmlhead3 = `</h2>` + `</span>` + `<!-- <ul id="nav" class="animated fadeOut" style="display: none;">-->` + `<span id="titlebar">` + `</span>` + `</nav>` + `<!--Menu For the Timeline Table-->` + `<div id="subnav">` + `<div id="tablemenuDIV">` + `<ol id="tablemenuOL">` + `<li style="width:;">` + `<button id="tablemenuX" class="navbuttons" style="font-weight: bolder; width: auto;padding: 0 5px;">&#9932;</button>` + `<button id="tablemenubutton1" class="navbuttons">SHOW ALL</button>` + `<button id="tablemenubutton2" class="navbuttons" style="display: none">HIDE ALL</button>` + `</li>` + `</ol>` + `</div>` + `<div id="sub-subnav2">` + `<div>` + `<div>` + `<button id="tablemenu" class="navbuttons navbuttons2">&#9776;</button>` + `<button id="summary" class="navbuttons navbuttons2">Summary</button>` + `<button id="showmain" class="navbuttons navbuttons2">Main Time</button>` + `<button id="showall" class="navbuttons navbuttons2">ShowAll</button>` + `</div>` + `<!--ONE ROW AT A TIME-->` + `<div style="display:;">` + `<button style="margin-left: 100px;" id="prevrow" class="navbuttons navbuttons2" onclick="prevRow">PREV-ROW</button>` + `<button id="nextrow" class="navbuttons navbuttons2" onclick="nextRow">NEXT-ROW</button>` + `<button class="navbuttons navbuttons2 resetBtn" style="margin-left: 10px;">RESET</button>` + `</div>` + `<!--ONE COLUMN AT A TIME-->` + `<div class="one-eventpertime-nav-top">` + `<span class="one-eventpertime-nav-top1">` + `<button class="navbuttons navbuttons2 prevBtn" onClick="prevCounter()">PREV</button>` + `<button class="navbuttons navbuttons2 nextBtn" onClick="nextCounter()">NEXT</button>` + `</span>` + `<span class="one-eventpertime-nav-top2">` + `<button class="navbuttons navbuttons2 prevBtn2" onClick="prevCounter()">PREV</button>` + `<button class="navbuttons navbuttons2 nextBtn2" onClick="nextCounter()">NEXT</button>` + `</span>` + `<button class="navbuttons navbuttons2 refreshBtn" style="margin-left: 10px;">REFRESH</button>` + `<button class="navbuttons navbuttons2 one-eventpertime-nav-top1" id="colSolo" onClick="colSolo()" style="background-color: #eaffc8; width: 66px;">SOLO-YES</button>` + `<button class="navbuttons navbuttons2 one-eventpertime-nav-top2" id="colSolo" onClick="colPreviousPreserve()" style="background-color:#ffe6ea; color: firebrick; width: 66px;">SOLO-NO</button>` + `</div>` + `<!--FOR EVENT COUNTER-->` + `<div id="eventcounter">0</div>` + `</div>` + `</div>` + `</div>` + `</header>` + `<main>` + `<!--TIMELINE TIMETABLE-->` + `<section>` + `<div class="timelineTableContainer">`;

//THE TIMELINETABL GETS INSERTED HERE

var htmldetails = `</div>` + `</section>` + `<section>` + `<div id="details">` + `<button id="detailsclosebutton" class="navbuttons">&#9932;</button>`

//THE DETAILS GET CREATED HERE

var detailsclass = `<div class="details`;                  //DETAILS CLASS INPUT CONTENT GETS INSERTED HERE
var detailsheading = `" style="display: ">` + `<h2>`;  //DETAILS HEADING INPUT CONTENT GETS INSERTED HERE
var detailstextarea = `</h2>` + `<p>`                      //DETAILS TEXTAREA CONTENT GETS INSERTED HERE
var detailstextareaclose = `</p>` + `</div>` + `</div>`;

var htmlfoot = `</section>` + `</main>` + `<footer>` + `<div class="one-eventpertime-nav-bottom">` + `<button class="navbuttons navbuttons2 prevBtn" onClick="prevCounter()">PREV</button>` + `<button class="navbuttons navbuttons2 refreshBtn" style="margin-left: 5px; margin-right: 5px;">REFRESH</button>` + `<button class="navbuttons navbuttons2 nextBtn" onClick="nextCounter()">NEXT</button>` + `</div>` + `<script src="../jscript/jquery-3.4.1.min.js">` + `</script><script src="../jscript/script.js">` + `</script><script src="../jscript/Sam-ColmunJS.js" type="text/javascript">` + `</script><script src="../jscript/contextMenu.js">` + `</script><script type="text/javascript" src="../jscript/tableNavigation.js">` + `</script>` + `</footer>` + `</body>` + `</html>`;